// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for android - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC9IDUBA-ltmPQPKDTMELj_uvy-Ud4xoXs',
    appId: '1:82634424469:web:8097a4378341273cfe5b9c',
    messagingSenderId: '82634424469',
    projectId: 'duality-dev-1337',
    authDomain: 'duality-dev-1337.firebaseapp.com',
    storageBucket: 'duality-dev-1337.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBGoJiaPJfq54NaugG6h_0NHqK56Q1LbhU',
    appId: '1:82634424469:ios:f7b98d0869b9c341fe5b9c',
    messagingSenderId: '82634424469',
    projectId: 'duality-dev-1337',
    storageBucket: 'duality-dev-1337.appspot.com',
    iosBundleId: 'com.example.duality',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBGoJiaPJfq54NaugG6h_0NHqK56Q1LbhU',
    appId: '1:82634424469:ios:f7b98d0869b9c341fe5b9c',
    messagingSenderId: '82634424469',
    projectId: 'duality-dev-1337',
    storageBucket: 'duality-dev-1337.appspot.com',
    iosBundleId: 'com.example.duality',
  );
}
